### ISSUE TITLE
Latest version doesn't import

### ISSUE THREAD

**Issue by gyoo18** [Nusiq/mcblend#109]
When I download and try to install the latest version, it doesn't show up in the list of addons. I tried running on 3.4, 3.3.2 LTS and 3.3.1 LTS and none of them worked. However, the version the 9.4.0 version imports both in 3.3 and 3.4.

**Comment by Nusiq** [comment]
It looks like Blender doesn't like when there are comment int the "bl_info" property that defines the add-on. I remember having some problems in the past. I'll send a fix soon.

**Comment by Nusiq** [comment]
It's possible that you'll need to delete `mcblend` folder from your addon installation path after the invalid installation. It's in: `%appdata%/Blender Foundation/Blender/3.3/scripts/addons` (maybe it's not necessary).

**Comment by Nusiq** [comment]
I just checked (I tired to install v10.0.0 from the zip file and than after it failed it installed v10.0.1 successfully on Blender 3.3). Deleting the old files manually is not necessary.

**Comment by gyoo18** [comment]
Just checked, it works, thanks!
