### ISSUE TITLE
Explain allowed parenting types in user manual

### ISSUE THREAD

**Issue by Nusiq** [Nusiq/mcblend#94]
Parenting the meshes to cubes with mesh deformation is probably the most popular way of dealing with bones in Blender, however Mcblend doesn't support any vertex deformations (it's not supported by Minecraft). User manual should clearly explain that using "Parent type: Bone" is the preferred way of parenting meshes to bones in Minecraft models.

There is some discussion about it in issue #92.

**Comment by sekretboi** [comment]
This helped a lot. Thank you so much my animations are working correctly now.

**Comment by Nusiq** [comment]
Old issue.
